import { Lighthouse, LighthouseFeature } from '@/types/lighthouse';

export const mockLighthouses: Lighthouse[] = [
  {
    id: 'pl-swinoujscie',
    name: 'Świnoujście',
    nameLocal: 'Latarnia Morska Świnoujście',
    country: 'PL',
    region: 'West Pomerania',
    coordinates: [14.2794, 53.9208],
    yearBuilt: 1857,
    heightM: 65,
    focalHeightM: 68,
    rangeNm: 26,
    lightCharacter: 'Fl W 5s',
    lightColor: 'white',
    construction: 'round brick tower',
    status: 'active',
    visitable: true,
    arlhsCode: 'POL-019',
    admiraltyCode: 'C2668',
    description: 'Najwyższa latarnia na polskim wybrzeżu.',
    imageUrl: 'https://upload.wikimedia.org/swinoujscie.jpg',
    wikipediaUrl: 'https://pl.wikipedia.org/wiki/...',
  },
  {
    id: 'pl-hel',
    name: 'Hel',
    nameLocal: 'Latarnia Morska Hel',
    country: 'PL',
    region: 'Pomerania',
    coordinates: [18.812, 54.608],
    yearBuilt: 1942,
    heightM: 41.5,
    rangeNm: 17,
    lightCharacter: 'Fl WR 5s',
    lightColor: 'red-white',
    construction: 'round concrete tower',
    status: 'active',
    visitable: true,
  },
  {
    id: 'pl-sopot',
    name: 'Sopot',
    country: 'PL',
    coordinates: [18.571, 54.445],
    yearBuilt: 1903,
    heightM: 15,
    rangeNm: 15,
    lightColor: 'white',
    construction: 'cast iron tower',
    status: 'inactive',
    visitable: false,
  },
  {
    id: 'fi-bengtskar',
    name: 'Bengtskär',
    country: 'FI',
    coordinates: [22.5, 59.725],
    yearBuilt: 1906,
    heightM: 52,
    rangeNm: 16,
    lightColor: 'white',
    construction: 'stone tower',
    status: 'active',
    visitable: true,
    description: 'Najdalej na południe wysunięta latarnia Finlandii.',
  },
  {
    id: 'ee-tahkuna',
    name: 'Tahkuna',
    country: 'EE',
    coordinates: [22.835, 59.237],
    yearBuilt: 1875,
    heightM: 42.6,
    rangeNm: 15,
    lightColor: 'green',
    construction: 'cast iron tower',
    status: 'active',
    visitable: true,
  },
];

export const mockFeature: LighthouseFeature = {
  type: 'Feature',
  geometry: {
    type: 'Point',
    coordinates: [14.2794, 53.9208],
  },
  properties: {
    id: 'pl-swinoujscie',
    name: 'Świnoujście',
    country: 'PL',
    yearBuilt: 1857,
    heightM: 65,
    rangeNm: 26,
    lightColor: 'white',
    status: 'active',
    visitable: true,
  },
};
